// Android home-screen widget plumbing: admin-managed content (Settings >
// App Widget) is fetched from the API, cached on the device for the widget's
// background redraws, and pushed to any widgets already on the home screen
// every time the app opens. All native calls are feature-detected so builds
// without the widget module (and iOS) degrade gracefully.

import { Platform } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import apiClient from '@services/api';
import { isWidgetPinSupported, requestWidgetPin } from '../../modules/widget-pin';

export interface AppWidgetConfig {
  enabled: boolean;
  title: string;
  message: string;
  messageUr: string;
}

const CACHE_KEY = 'fb_app_widget_config';
/** Must match app.json > plugins > react-native-android-widget > widgets[0].name */
export const WIDGET_NAME = 'FreshBazar';
/** Provider class generated by the widget plugin: <package>.widget.<name> */
const WIDGET_PROVIDER_CLASS = 'com.freshbazar.customer.widget.FreshBazar';

export const WIDGET_DEFAULTS: AppWidgetConfig = {
  enabled: true,
  title: 'Fresh Bazar',
  message: 'Taza sabzi & fruits — free delivery on Rs. 500+',
  messageUr: 'تازہ سبزیاں اور پھل — آپ کے دروازے پر',
};

export async function getCachedWidgetConfig(): Promise<AppWidgetConfig> {
  try {
    const raw = await AsyncStorage.getItem(CACHE_KEY);
    if (raw) return { ...WIDGET_DEFAULTS, ...JSON.parse(raw) };
  } catch {
    /* cache unreadable — use defaults */
  }
  return WIDGET_DEFAULTS;
}

/**
 * Fetch the admin-managed widget content, cache it, and redraw any widgets
 * already placed on the home screen. Call on app open.
 */
export async function refreshWidgetConfig(): Promise<AppWidgetConfig> {
  try {
    const response = await apiClient.get('/site-settings/app-widget');
    const raw = response.data?.data || {};
    const config: AppWidgetConfig = {
      enabled: raw.enabled !== false && raw.enabled !== 'false',
      title: String(raw.title || WIDGET_DEFAULTS.title),
      message: String(raw.message || WIDGET_DEFAULTS.message),
      messageUr: String(raw.message_ur || raw.messageUr || WIDGET_DEFAULTS.messageUr),
    };
    await AsyncStorage.setItem(CACHE_KEY, JSON.stringify(config));
    await redrawHomeScreenWidgets(config);
    return config;
  } catch {
    return getCachedWidgetConfig();
  }
}

/** Push fresh content into widgets already on the home screen (if any). */
async function redrawHomeScreenWidgets(config: AppWidgetConfig): Promise<void> {
  if (Platform.OS !== 'android') return;
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const { requestWidgetUpdate } = require('react-native-android-widget');
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const React = require('react');
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const { FreshBazarWidget } = require('../widgets/FreshBazarWidget');
    await requestWidgetUpdate({
      widgetName: WIDGET_NAME,
      renderWidget: () => React.createElement(FreshBazarWidget, { config }),
      widgetNotFound: () => {},
    });
  } catch {
    /* widget module not in this build — nothing to redraw */
  }
}

export type AddWidgetResult = 'pinned' | 'manual' | 'unsupported';

/**
 * Ask Android to place the widget automatically (system permission dialog).
 * 'pinned'      — dialog shown; Android adds the widget on approval.
 * 'manual'      — device/launcher can't auto-pin; show manual steps.
 * 'unsupported' — iOS or an app build without the widget module.
 */
export async function requestAddWidget(): Promise<AddWidgetResult> {
  if (Platform.OS !== 'android') return 'unsupported';
  try {
    // Ensure the widget module exists in this build before offering the pin.
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    require('react-native-android-widget');
  } catch {
    return 'unsupported';
  }
  if (isWidgetPinSupported() && requestWidgetPin(WIDGET_PROVIDER_CLASS)) {
    return 'pinned';
  }
  return 'manual';
}
