// ============================================================================
// PERMISSIONS REGISTRY
// ----------------------------------------------------------------------------
// Single source of truth for permission codes the backend understands.
// Mirrors the seed in database/migrations/03-unit-pricing-and-admin-roles.sql.
// ============================================================================

export const PERMISSION_CODES = [
  'orders.view',
  'orders.update',
  'orders.cancel',
  'orders.refund',
  'orders.assign_rider',
  'products.view',
  'products.create',
  'products.update',
  'products.delete',
  'stock.adjust',
  'categories.manage',
  'customers.view',
  'customers.update',
  'customers.export',
  'customers.delete',
  'addresses.view',
  'addresses.update',
  'riders.view',
  'riders.manage',
  'settings.view',
  'settings.update',
  'settings.delivery.view',
  'settings.delivery.update',
  'settings.timeslots.view',
  'settings.timeslots.manage',
  'settings.business_hours.view',
  'settings.business_hours.update',
  'settings.banner.view',
  'settings.banner.update',
  'settings.hero.view',
  'settings.hero.update',
  'settings.brand.view',
  'settings.brand.update',
  'settings.favicon.view',
  'settings.favicon.update',
  'settings.cities.view',
  'settings.cities.manage',
  'settings.delivery_zones.view',
  'settings.delivery_zones.manage',
  'coupons.view',
  'coupons.manage',
  'reviews.view',
  'reviews.manage',
  'complaints.view',
  'complaints.manage',
  'tips.view',
  'tips.manage',
  'rider_applications.view',
  'rider_applications.manage',
  'roles.manage',
  'admins.manage',
  'ocp.manage',
  'ocp.stock.send',
  'ocp.settlements.receive',
  'ocp.shortages.manage',
  'finance.expenses.view',
  'finance.expenses.create',
  'finance.stock_purchase.create',
  'finance.rider_payments.create',
  'finance.rider_cash.receive',
  'finance.workers.manage',
  'finance.profit.view',
  'finance.profit.manage',
  'finance.shareholders.view',
  'finance.shareholders.manage',
  'finance.shareholders.pay',
  'franchise.view',
  'franchise.manage',
  'marketing.view',
  'marketing.manage',
] as const;

export type PermissionCode = (typeof PERMISSION_CODES)[number];

export interface PermissionCatalogueRow {
  code: PermissionCode;
  description: string;
  category: string;
}

export const PERMISSION_CATALOGUE: PermissionCatalogueRow[] = [
  { code: 'orders.view',         description: 'View orders',                     category: 'Orders' },
  { code: 'orders.update',       description: 'Update order status',             category: 'Orders' },
  { code: 'orders.cancel',       description: 'Cancel orders',                   category: 'Orders' },
  { code: 'orders.refund',       description: 'Refund orders',                   category: 'Orders' },
  { code: 'orders.assign_rider', description: 'Assign rider to orders',          category: 'Orders' },
  { code: 'products.view',       description: 'View products',                   category: 'Products' },
  { code: 'products.create',     description: 'Create products',                 category: 'Products' },
  { code: 'products.update',     description: 'Update products',                 category: 'Products' },
  { code: 'products.delete',     description: 'Delete/deactivate products',      category: 'Products' },
  { code: 'stock.adjust',        description: 'Emergency stock correction',       category: 'Products' },
  { code: 'categories.manage',   description: 'Manage categories',               category: 'Products' },
  { code: 'customers.view',      description: 'View customers',                  category: 'Customers' },
  { code: 'customers.update',    description: 'Update customers',                category: 'Customers' },
  { code: 'customers.export',    description: 'Export customer data (PII CSV)',  category: 'Customers' },
  { code: 'customers.delete',    description: 'Delete / anonymize customers',    category: 'Customers' },
  { code: 'addresses.view',      description: 'View customer addresses',         category: 'Customers' },
  { code: 'addresses.update',    description: 'Update customer addresses',       category: 'Customers' },
  { code: 'riders.view',         description: 'View riders',                     category: 'Riders' },
  { code: 'riders.manage',       description: 'Approve / manage riders',         category: 'Riders' },
  { code: 'settings.view',       description: 'View all settings (legacy full access)', category: 'Settings' },
  { code: 'settings.update',     description: 'Update all settings (legacy full access)', category: 'Settings' },
  { code: 'settings.delivery.view',       description: 'View delivery charge settings', category: 'Settings' },
  { code: 'settings.delivery.update',     description: 'Update delivery charge settings', category: 'Settings' },
  { code: 'settings.timeslots.view',      description: 'View delivery time slots', category: 'Settings' },
  { code: 'settings.timeslots.manage',    description: 'Manage delivery time slots', category: 'Settings' },
  { code: 'settings.business_hours.view', description: 'View business hours', category: 'Settings' },
  { code: 'settings.business_hours.update', description: 'Update business hours', category: 'Settings' },
  { code: 'settings.banner.view',         description: 'View website banner text', category: 'Settings' },
  { code: 'settings.banner.update',       description: 'Update website banner text', category: 'Settings' },
  { code: 'settings.hero.view',           description: 'View homepage hero image', category: 'Settings' },
  { code: 'settings.hero.update',         description: 'Update homepage hero image (per city)', category: 'Settings' },
  { code: 'settings.brand.view',          description: 'View brand logo', category: 'Settings' },
  { code: 'settings.brand.update',        description: 'Update brand logo (API: super admin only)', category: 'Settings' },
  { code: 'settings.favicon.view',        description: 'View brand favicon', category: 'Settings' },
  { code: 'settings.favicon.update',      description: 'Update brand favicon (API: super admin only)', category: 'Settings' },
  { code: 'settings.cities.view',         description: 'View service cities', category: 'Settings' },
  { code: 'settings.cities.manage',       description: 'Manage service cities', category: 'Settings' },
  { code: 'settings.delivery_zones.view', description: 'View delivery zones', category: 'Settings' },
  { code: 'settings.delivery_zones.manage', description: 'Manage delivery zones', category: 'Settings' },
  { code: 'coupons.view',        description: 'View discount coupons',            category: 'Coupons' },
  { code: 'coupons.manage',      description: 'Create / manage discount coupons', category: 'Coupons' },
  { code: 'reviews.view',        description: 'View product / rider / service reviews', category: 'Support' },
  { code: 'reviews.manage',      description: 'Moderate / reply to reviews',      category: 'Support' },
  { code: 'complaints.view',     description: 'View customer complaints',         category: 'Support' },
  { code: 'complaints.manage',   description: 'Respond to / resolve complaints',  category: 'Support' },
  { code: 'tips.view',           description: 'View user guidance tips',          category: 'Settings' },
  { code: 'tips.manage',         description: 'Add / edit / pause user guidance tips', category: 'Settings' },
  { code: 'rider_applications.view',   description: 'View rider applications',     category: 'Riders' },
  { code: 'rider_applications.manage', description: 'Manage rider applications + page content', category: 'Riders' },
  { code: 'roles.manage',        description: 'Create / manage admin roles',     category: 'Admins' },
  { code: 'admins.manage',       description: 'Invite / manage admin users',     category: 'Admins' },
  { code: 'ocp.manage',              description: 'Create / manage Order Collection Points', category: 'OCP' },
  { code: 'ocp.stock.send',          description: 'Send stock to an OCP',                    category: 'OCP' },
  { code: 'ocp.settlements.receive', description: 'Receive OCP cash settlements',            category: 'OCP' },
  { code: 'ocp.shortages.manage',    description: 'View and resolve OCP stock shortages',    category: 'OCP' },
  { code: 'finance.expenses.view',          description: 'View finance expenses',                 category: 'Finance' },
  { code: 'finance.expenses.create',        description: 'Create non-stock expenses',             category: 'Finance' },
  { code: 'finance.stock_purchase.create',  description: 'Enter stock purchases',                 category: 'Finance' },
  { code: 'finance.rider_payments.create',  description: 'Record rider payments',                 category: 'Finance' },
  { code: 'finance.rider_cash.receive',     description: 'Receive COD cash from riders',          category: 'Finance' },
  { code: 'finance.workers.manage',         description: 'Manage workers, attendance and pay',     category: 'Finance' },
  { code: 'finance.profit.view',            description: 'View profit reports',                    category: 'Finance' },
  { code: 'finance.profit.manage',          description: 'Manage profit-sharing settings',         category: 'Finance' },
  { code: 'finance.shareholders.view',      description: 'View shareholders and payouts',          category: 'Finance' },
  { code: 'finance.shareholders.manage',    description: 'Create/edit shareholders',               category: 'Finance' },
  { code: 'finance.shareholders.pay',       description: 'Record shareholder payouts',             category: 'Finance' },
  { code: 'franchise.view',      description: 'View franchise inquiries',                  category: 'Franchise' },
  { code: 'franchise.manage',    description: 'Update / resolve franchise inquiries',      category: 'Franchise' },
  { code: 'marketing.view',      description: 'View abandoned carts and marketing settings', category: 'Marketing' },
  { code: 'marketing.manage',    description: 'Run cart reminders / update marketing settings', category: 'Marketing' },
];
